/**
 * types/index.ts - TypeScript Type Definitions
 * 
 * This file contains all shared TypeScript interfaces used across
 * the AutoTrader AI frontend application. Centralizing types here:
 * - Ensures consistency across components
 * - Provides single source of truth for data shapes
 * - Enables IDE autocompletion and type checking
 * - Documents the API contract between frontend and backend
 * 
 * Type Categories:
 * - Recommendation: AI-generated trading signals
 * - Regime: Market regime classification
 * - UserConfig: User preferences and risk settings
 * - SessionInfo: Authentication state
 * - ConnectorStatus: Data connector health status
 * 
 * @see services/api.ts for API functions using these types
 */

/**
 * RegimeInfo - Market regime classification for a symbol.
 * 
 * The regime model classifies market conditions across 4 dimensions
 * and adapts signal weights, position sizing, and stop-loss recommendations.
 */
export interface RegimeInfo {
  /** Human-readable regime label (e.g., "Volatile / Bearish / Earnings") */
  label: string
  /** Overall risk level: "normal" or "high" */
  risk_level: 'normal' | 'high'
  /** Volatility regime: low, normal, high, extreme */
  volatility: 'low' | 'normal' | 'high' | 'extreme'
  /** Trend regime */
  trend: 'strong_uptrend' | 'uptrend' | 'mean_reverting' | 'choppy' | 'downtrend' | 'strong_downtrend'
  /** Liquidity regime */
  liquidity: 'high' | 'normal' | 'thin' | 'illiquid'
  /** Information/news regime */
  information: 'quiet' | 'normal' | 'news_driven' | 'social_driven' | 'earnings'
  /** Risk score from 0 to 1 (higher = riskier) */
  risk_score: number
  /** Warnings for current regime */
  warnings: string[]
}

/**
 * PositionSizingInfo - Position sizing recommendation based on regime.
 */
export interface PositionSizingInfo {
  /** Position size multiplier (1.0 = standard, 0.5 = half size) */
  size_multiplier: number
  /** Maximum position as % of portfolio */
  max_position_percent: number
  /** Number of entries to scale in */
  scale_in_entries: number
  /** Explanation for sizing recommendation */
  reasoning: string
}

/**
 * StopLossInfo - Stop-loss recommendation based on regime.
 */
export interface StopLossInfo {
  /** Stop-loss as ATR multiplier */
  atr_multiplier: number
  /** Stop-loss as % from entry */
  percent_from_entry: number
  /** Whether to use trailing stop */
  use_trailing_stop: boolean
  /** Target risk:reward ratio */
  risk_reward_ratio: number
  /** Explanation for stop-loss recommendation */
  reasoning: string
}

/**
 * SignalWeightsInfo - Regime-adaptive signal weights.
 */
export interface SignalWeightsInfo {
  news_sentiment: number
  news_momentum: number
  technical_trend: number
  technical_momentum: number
  confidence_multiplier: number
}

/**
 * RegimeResponse - Full regime classification response from API.
 */
export interface RegimeResponse {
  symbol: string
  regime: RegimeInfo
  signal_weights: SignalWeightsInfo
  position_sizing?: PositionSizingInfo
  stop_loss?: StopLossInfo
  timestamp: string
}

/**
 * Recommendation - AI-generated trading recommendation for a stock.
 * 
 * Generated by the ML Recommendation Engine and served via the
 * Recommendation Service. Each recommendation includes:
 * - Trading action (BUY/SELL/HOLD)
 * - Confidence level from the ML model
 * - Suggested order parameters
 * - Human-readable explanation (Explainable AI)
 * 
 * Lifecycle:
 * 1. ML pipeline generates recommendation
 * 2. Stored in PostgreSQL recommendations table
 * 3. Fetched by frontend via /api/v1/recommendations
 * 4. Displayed in Dashboard with action buttons
 * 
 * @see Dashboard.tsx for display logic
 * @see recommendationApi for data fetching
 */
export interface Recommendation {
  /** Stock ticker symbol (e.g., 'AAPL', 'GOOGL') */
  symbol: string
  
  /** 
   * AI's recommended action:
   * - BUY: Model suggests purchasing shares
   * - SELL: Model suggests selling existing shares
   * - HOLD: Model suggests no action
   */
  action: 'BUY' | 'SELL' | 'HOLD'
  
  /** 
   * Model's confidence in the recommendation (0.0 to 1.0)
   * Higher values indicate stronger signals
   * Typically: >0.8 = high confidence, 0.6-0.8 = moderate, <0.6 = low
   */
  confidence: number
  
  /** Suggested order parameters if user decides to act */
  suggestedOrder: {
    /** Order type: LIMIT (specified price) or MARKET (current price) */
    type: 'LIMIT' | 'MARKET'
    /** Suggested price for LIMIT orders */
    price: number
    /** Suggested number of shares to trade */
    quantity: number
  }
  
  /** 
   * Explainable AI output - human-readable reasoning
   * Generated by the Explainability Service using LLM
   */
  explanation: {
    /** Human-readable summary of why this action is recommended */
    summary: string
    /** LLM-generated detailed analysis */
    llm_analysis?: string
    /** Overall recommendation score (-1 to 1) */
    score?: number
    /** Recommendation action */
    action?: string
    /** Key factors driving the recommendation */
    factors?: string[]
    /** Individual signal contributions to the recommendation */
    signals?: {
      /** Relative Strength Index (0-100, oversold <30, overbought >70) */
      rsi?: number
      /** News sentiment score (-1 to 1, negative to positive) */
      newsSentiment?: number
      /** Social media momentum indicator */
      socialMomentum?: number
    }
    /** News analytics data */
    news?: {
      articles_24h?: number
      articles_7d?: number
      sentiment_1d?: number
      sentiment_trend?: string
    }
    /** Technical analysis data */
    technical?: {
      price?: number
      change_1d?: string
      change_5d?: string
      rsi?: number
      trend?: string
      volatility?: string
    }
    /** Recent news articles with links */
    recent_articles?: {
      title: string
      source: string
      sentiment: string
      url?: string
    }[]
  }
}

/**
 * UserConfig - User's trading preferences and risk management settings.
 * 
 * These settings control how the AI generates recommendations and
 * what constraints apply to trade execution. Configured during
 * onboarding and editable in Settings.
 * 
 * Stored in PostgreSQL user_configurations table.
 * 
 * @see Settings.tsx for configuration UI
 * @see configApi for CRUD operations
 */
export interface UserConfig {
  /** 
   * Stock symbols the user wants to track and receive recommendations for
   * Example: ['AAPL', 'GOOGL', 'MSFT', 'TSLA']
   */
  symbols: string[]
  
  /** Risk management constraints to prevent overexposure */
  riskLimits: {
    /** Maximum % of portfolio in a single position (1-100) */
    maxPositionPct: number
    /** Maximum number of trades allowed per day */
    maxTradesPerDay: number
  }
  
  /** 
   * Weights for different signal types in recommendation scoring
   * Values should sum to 1.0 (or be normalized by backend)
   */
  signalWeights: {
    /** Weight for technical indicators (RSI, MACD, etc.) */
    technical: number
    /** Weight for news sentiment analysis */
    news: number
    /** Weight for social media signals */
    social: number
  }
}

/**
 * SessionInfo - Current authentication and connection status.
 * 
 * Returned by GET /api/v1/auth/session to inform the frontend
 * about the user's current state. Used to determine:
 * - Whether to show protected content
 * - Whether trade execution is available
 * - When to prompt for re-authentication
 * 
 * @see AuthContext.tsx for state management
 * @see authApi.getSession for data fetching
 */
export interface SessionInfo {
  /** UUID of the authenticated user */
  userId: string
  
  /** Whether the user has a valid session */
  authenticated: boolean
  
  /** 
   * Whether user has connected a brokerage account (e.g., Robinhood)
   * Required for trade execution
   */
  brokerageConnected: boolean
  
  /** 
   * ISO timestamp when brokerage OAuth token expires
   * Null if no brokerage connected
   * Frontend should prompt re-auth before this time
   */
  brokerageTokenExpiresAt: string | null
}

/**
 * StockRecommendationHistory - Historical recommendation from the database.
 * 
 * Generated by the ML pipeline twice daily (7:30 AM & 12:00 PM PST) and stored in PostgreSQL.
 * The system keeps the last 10 recommendations per symbol for historical view.
 * 
 * Scoring System:
 * - BUY: normalized score > 0.8
 * - SELL: normalized score < 0.5
 * - HOLD: 0.5 <= normalized score <= 0.8
 * 
 * @see StockRecommendations.tsx for display
 * @see recommendationApi.getHistory for data fetching
 */
export interface StockRecommendationHistory {
  /** Unique recommendation ID (UUID) */
  id: string
  
  /** Stock ticker symbol (e.g., 'AAPL', 'GOOGL') */
  symbol: string
  
  /** 
   * AI's recommended action:
   * - BUY: normalized score > 0.8
   * - SELL: normalized score < 0.5
   * - HOLD: 0.5 <= normalized score <= 0.8
   */
  action: 'BUY' | 'SELL' | 'HOLD'
  
  /** Raw score from -1 (strong sell) to 1 (strong buy) */
  score: number | null
  
  /** Normalized score from 0 to 1 for display */
  normalizedScore: number | null
  
  /** Model's confidence in the recommendation (0.0 to 1.0) */
  confidence: number | null
  
  /** Stock price when recommendation was generated */
  priceAtRecommendation: number | null
  
  /** News sentiment component score */
  newsSentimentScore: number | null
  
  /** News momentum component score */
  newsMomentumScore: number | null
  
  /** Technical trend component score */
  technicalTrendScore: number | null
  
  /** Technical momentum component score */
  technicalMomentumScore: number | null
  
  /** RSI indicator value (0-1, oversold <0.3, overbought >0.7) */
  rsi: number | null
  
  /** MACD histogram value (normalized) */
  macdHistogram: number | null
  
  /** Price vs SMA20 ratio */
  priceVsSma20: number | null
  
  /** 1-day news sentiment score */
  newsSentiment1d: number | null
  
  /** Number of news articles in last 24 hours */
  articleCount24h: number | null
  
  /** Human-readable explanation of the recommendation */
  explanation: {
    /** LLM-generated summary explaining the recommendation */
    summary: string
    score?: number
    action?: string
    /** Key factors that drove this recommendation */
    factors?: string[]
    /** Recent news articles used in the analysis */
    recent_articles?: {
      title: string
      source: string
      sentiment: string
      url?: string
    }[]
    /** LLM-powered detailed analysis */
    llm_analysis?: string
    news?: {
      articles_24h?: number
      articles_7d?: number
      sentiment_1d?: number
      sentiment_trend?: string
    }
    technical?: {
      price?: number
      change_1d?: string
      change_5d?: string
      rsi?: number
      trend?: string
      volatility?: string
    }
  } | null
  
  /** Data sources used for this recommendation */
  dataSourcesUsed: string[] | null
  
  /** ISO timestamp when recommendation was generated */
  generatedAt: string | null
  
  /** ISO timestamp when record was created in database */
  createdAt: string | null
}

/**
 * Response from the recommendation history API endpoint.
 */
export interface RecommendationHistoryResponse {
  /** Stock ticker symbol */
  symbol: string
  
  /** List of historical recommendations (up to 10) */
  recommendations: StockRecommendationHistory[]
  
  /** Number of recommendations returned */
  count: number
}

/**
 * ConnectorStatus - Status of a data connector.
 * 
 * Represents the current health status of a data connector used
 * by the recommendation engine. Updated by the health check service
 * every 3 hours.
 * 
 * @see Connectors.tsx for display logic
 * @see connectorApi for data fetching
 */
export interface ConnectorStatus {
  /** Internal connector name (e.g., 'polygon', 'alpha_vantage') */
  name: string
  
  /** Connector category: 'paid', 'free', 'social', 'disabled' */
  type: 'paid' | 'free' | 'social' | 'disabled'
  
  /** Human-readable display name */
  displayName: string
  
  /** 
   * Current connection status:
   * - connected: Working properly
   * - disconnected: No API key or not configured
   * - error: API error or authentication failure
   * - disabled: Intentionally disabled
   * - unknown: Not yet checked
   */
  status: 'connected' | 'disconnected' | 'error' | 'disabled' | 'unknown'
  
  /** Human-readable status message */
  statusMessage: string | null
  
  /** ISO timestamp of last health check */
  lastCheckAt: string | null
  
  /** ISO timestamp of last successful connection */
  lastSuccessAt: string | null
  
  /** ISO timestamp of last error */
  lastErrorAt: string | null
  
  /** Error message from last failure */
  lastErrorMessage: string | null
  
  /** Number of articles fetched in last check */
  articlesFetched: number
  
  /** Response time in milliseconds */
  responseTimeMs: number | null
  
  /** Whether this connector requires an API key */
  requiresApiKey: boolean
  
  /** Whether an API key is configured */
  hasApiKey: boolean
  
  /** ISO timestamp when status was last updated */
  updatedAt: string | null
}

/**
 * Response from the connector status API endpoint.
 */
export interface ConnectorStatusResponse {
  /** List of all connector statuses */
  connectors: ConnectorStatus[]
  
  /** ISO timestamp of last overall update */
  lastUpdated: string | null
}

/**
 * Summary statistics for connectors.
 */
export interface ConnectorSummary {
  connected: number
  disconnected: number
  error: number
  disabled: number
  unknown: number
  total: number
}
