#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║        AutoTrader AI - Push to GitHub Helper                     ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "🔑 You need a GitHub Personal Access Token"
echo ""
echo "If you don't have one:"
echo "  1. Go to: https://github.com/settings/tokens/new"
echo "  2. Note: AutoTrader-AI"
echo "  3. Select scope: ✅ repo"
echo "  4. Click 'Generate token'"
echo "  5. Copy the token (starts with ghp_)"
echo ""
echo "Now run this command:"
echo ""
echo "  git push -u origin main"
echo ""
echo "When prompted:"
echo "  Username: vsahdev-bit"
echo "  Password: [paste your token]"
echo ""
echo "After successful push, visit:"
echo "  https://github.com/vsahdev-bit/AutoTrader-AI"
echo ""
